function pl = local_prob5(lc, lcNull)
% calculate significance for local correlation using a null distributio for
% estimation of probability
% SYNTAX: pl = local_prob5(lc, lcNull)
% 
% INPUTS: 
%       lc: a nSim-by-nstep matrix, the observed local correlation
%               nSim is the number of Simuations to generate the null
%               nstep is the grid size for evaluation of local correlation.
%       lcNull: is null distribution of local correlation,generated by
%               nSim number of permutation replications
% OUTPUTs: pl: estimated achineved significance for local correlation
%
% REFERENCE:
% Chen YA, Almeida JS, Richards AJ, Müller P, Carroll RJ. and Baerbel 
% Rohrer. A nonparametric approach to detect local correlation in gene
% expression, published in the Journal of Computational and Gradphical
% Statistics
%
% Y. Ann Chen, Moffitt Cancer Center, ann.chen@moffitt.org



nSim = size(lcNull,1);
nstep =size(lc,2);


for j = 1:nstep
    pl(1,j) = sum(abs(lcNull(:,j))>abs(lc(1,j)))/nSim;
end
